$ANSIBLE_VAULT;1.1;AES256
30386539306236376532393063383932346562636263393737326362643162313463646566643133
3463663865616630363966613538343737623738343733660a326137373264383030303535326161
61613130323133646235656665366265623365353264383837613761393630356230343736663337
3238663736393835660a653230646630633866616539646335663237373564393961323037306638
35396332653066353135363138343865396231636234643531343139656565613235626339316631
30346336613237313339666662323639636637396135633438386364313635306338663266393762
61303863656166353562336261616566643663353764346561666462336636626231303336626333
38303066353133396665386366326132636638646538623765366432366163616336613234623534
66356638636133363163343830313034613463626435333136613965623661613234323339336639
36336633323365653634343863353130343633366466336634326639303133313763366531333331
34643964613066663631666630636266633537363962303963643662633661646236643466383163
64616562366430633565393334623064333631653138333034643861633336376165666434356137
3235
