$ANSIBLE_VAULT;1.1;AES256
36323230303265383634383964333166643030656161643563323136633361393436316634323537
6436313332613463623638326534663662313332333635340a303030653762346437323833383239
64306562346363373138353639303263333665303264356131323438366438346561613062363635
6564613038323936630a626634376231383934653561353239663937363962383434393736316531
35363062343366633438396437633361623937613065376461366436646432313236656163383663
65656662363263626338613938303730626465613335326366366664323938383235326335323261
34643864363663373764353264373463313737393762613234396231343937626263646636626336
63326666383664633531373231356639643537386131323937633636666662356139636236383439
32326463303962633362323631363633323839636362376233613331386538646132346335363632
32323434616436633838646665636337666539626637613130663463646463333365646338393139
33333831353032343262373134646264336630353337623638346362626461653166326165383864
61626461643939626535616263613261636531316365303738666333346533346330633937336237
33333937633961663337656466623332643838356334373263333231613061396263643332376566
65633065613539623837366638393064316165653465363234373432646162656565306134313266
37343437393365366438333432333338383337363335653437393635396636366236303432393136
65353830366465643433383263326239326637626664363735303034636565336137666661666136
33353336363566303531333933636137396461623436613639326630383066656662623132636339
31386233636234613836663661356236313563323963333036373261643066636131633233396436
33656238396438363537303037633664656239616130643662316431366539396638343038656530
65303137323266356435616462313839356666383961303930313037393336643962656362663035
61613836303561316333643034393635316133653732333461303361343236373436333234363436
39653465343236316665323036326330643161363765313532666538343738366534343932626462
643239633763666661306538653639316432
